stages:
- build
- deploy

variables:
  NODE_ENV: production

cache:
  paths:
  - node_modules/

build:
  stage: build
  image: node:20
  script:
  - npm install
  - npm run build
  - npm run export
  artifacts:
    paths:
    - out

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
  - apk add --no-cache openssh-client rsync
  script:
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
  - rsync -avz --delete out/ $EC2_USER@$EC2_HOST:/var/www/rs-deliv
  only:
  - main
